const NewsData = {
  items: [
    {
      id: 37931,
      tipo: "Not\u00EDcia",
      titulo: "Servidores do IBGE no RS se mobilizam para ajudar desabrigados nas enchentes",
      introducao: "Servidores da Superintend\u00EAncia RS e da Ag\u00EAncia de Lajeado levaram solidariedade e mantimentos \u00E0s v\u00EDtimas das enchentes que atingiram o Vale do Taquari - Foto - Acervo IBGE Na \u00FAltima semana, servidores do IBGE no Rio Grande do Sul se mobilizaram para...",
      data_publicacao: "19/09/2023 10:00:00",
      produto_id: 0,
      produtos: "",
      editorias: "ibge",
      imagens: "{\"image_intro\":\"images\\/agenciadenoticias\\/ibge\\/2023_09\\/Doaes_THUMB.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/ibge\\/2023_09\\/Doaes_HOME.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      produtos_relacionados: "",
      destaque: true,
      link: "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37931-servidores-do-ibge-no-rs-se-mobilizam-para-ajudar-desabrigados-nas-enchentes.html"
    },
    {
      id: 37917,
      tipo: "Not\u00EDcia",
      titulo: "IBGE: mais de 180 mil candidatos far\u00E3o provas neste domingo, em todo o pa\u00EDs",
      introducao: "Processos seletivos receberam mais de 180 mil inscri\u00E7\u00F5es - Foto: Acervo IBGE A partir das 9h do pr\u00F3ximo domingo, come\u00E7am em todo o pa\u00EDs as provas para Agente de Pesquisas e Mapeamento (APM) e Supervisor de Coleta e Qualidade (SCQ) do IBGE. Ser\u00E3o 181.610...",
      data_publicacao: "15/09/2023 14:00:00",
      produto_id: 0,
      produtos: "",
      editorias: "ibge",
      imagens: "{\"image_intro\":\"images\\/agenciadenoticias\\/ibge\\/2023_09\\/PSS-APM_THUMB.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/ibge\\/2023_09\\/PSS-APM_HOME.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      produtos_relacionados: "",
      destaque: true,
      link: "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37917-ibge-mais-de-180-mil-candidatos-farao-provas-neste-domingo-em-todo-o-pais.html"
    },
    {
      id: 37913,
      tipo: "Not\u00EDcia",
      titulo: "Taxa de sindicaliza\u00E7\u00E3o cai a 9,2% em 2022, menor n\u00EDvel da s\u00E9rie",
      introducao: "Em 2022, menos de 10% dos trabalhadores eram sindicalizados, chegando ao menor contingente da s\u00E9rie iniciada em 2012 - Foto: Rovena Rosa/Ag\u00EAncia Brasil Em 2022, das 99,6 milh\u00F5es de pessoas ocupadas, 9,2% (9,1 milh\u00F5es de pessoas) eram associadas a...",
      data_publicacao: "15/09/2023 10:00:00",
      produto_id: 17270,
      produtos: "17270|Divulga\u00E7\u00E3o anual#pnadc3|pnad-continua|2511",
      editorias: "sociais",
      imagens: "{\"image_intro\":\"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_09\\/PNAD-Sindical_THUMB_Rovena-Rosa-Ag\u00EAncia-Brasil.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/estatisticas_sociais\\/2023_09\\/PNAD-Sindical_HOME_Rovena-Rosa-Ag\u00EAncia-Brasil.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      produtos_relacionados: "17270",
      destaque: true,
      link: "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37913-taxa-de-sindicalizacao-cai-a-9-2-em-2022-menor-nivel-da-serie.html"
    },
    {
      id: 37908,
      tipo: "Not\u00EDcia",
      titulo: "Volume de vendas no com\u00E9rcio tem alta de 0,7% em julho",
      introducao: "Setor de artigos de uso pessoal e dom\u00E9stico influenciou no resultado do com\u00E9rcio de julho - Foto: Alerrandre Barros/Ag\u00EAncia IBGE Not\u00EDcias O com\u00E9rcio varejista nacional teve alta de 0,7% em julho, ap\u00F3s varia\u00E7\u00E3o de 0,1% em junho. Com isso, a m\u00E9dia m\u00F3vel...",
      data_publicacao: "15/09/2023 09:00:00",
      produto_id: 9227,
      produtos: "9227|Pesquisa Mensal de Com\u00E9rcio|pesquisa-mensal-de-comercio|2075",
      editorias: "economicas",
      imagens: "{\"image_intro\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PMC_Thumb_Alerrandre-Barros.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PMC_Home_Alerrandre-Barros.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      produtos_relacionados: "9227",
      destaque: true,
      link: "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37908-volume-de-vendas-no-comercio-tem-alta-de-0-7-em-julho.html"
    },
    {
      id: 37907,
      tipo: "Release",
      titulo: "Vendas no varejo sobem 0,7% em julho",
      introducao: "Em julho de 2023, o volume de vendas do com\u00E9rcio varejista teve alta de 0,7% frente a junho, na s\u00E9rie com ajuste sazonal. A m\u00E9dia m\u00F3vel trimestral foi de 0,1%. Frente a julho de 2022, houve alta de 2,4%, segunda alta consecutiva nessa compara\u00E7\u00E3o. O...",
      data_publicacao: "15/09/2023 09:00:00",
      produto_id: 9227,
      produtos: "9227|Pesquisa Mensal de Com\u00E9rcio|pesquisa-mensal-de-comercio|2075",
      editorias: "economicas",
      imagens: "{\"image_intro\":\"images\\/agenciadenoticias\\/releases\\/PMC_release.png\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/releases\\/PMC_release.png\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      produtos_relacionados: "9227",
      destaque: true,
      link: "http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37907-vendas-no-varejo-sobem-0-7-em-julho.html"
    },
    {
      id: 37894,
      tipo: "Not\u00EDcia",
      titulo: "Em 2022, Sorriso (MT) manteve a lideran\u00E7a na produ\u00E7\u00E3o agr\u00EDcola",
      introducao: "Com crescimento de 1,3%, valor de produ\u00E7\u00E3o da soja chegou a R$ 345,4 bilh\u00F5es em 2022 - Foto: Secom/MT Valor de produ\u00E7\u00E3o e safra de gr\u00E3os batem recorde em 2022 O valor de produ\u00E7\u00E3o das principais culturas agr\u00EDcolas do Brasil atingiu o recorde de R$ 830,1...",
      data_publicacao: "14/09/2023 10:00:00",
      produto_id: 0,
      produtos: "9117|Culturas tempor\u00E1rias e permanentes #PAM1|producao-agricola-municipal-culturas-temporarias-e-permanentes|2046;9119|Cereais, leguminosas e oleaginosas#PAM2|producao-agricola-municipal-cereais-leguminosas-e-oleaginosas|2046",
      editorias: "economicas",
      imagens: "{\"image_intro\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PAM_THUMB_Secom-MT.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PAM_HOME_Secom-MT.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      produtos_relacionados: "9117, 9119",
      destaque: true,
      link: "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37894-em-2022-sorriso-mt-manteve-a-lideranca-na-producao-agricola.html"
    },
    {
      id: 37899,
      tipo: "Not\u00EDcia",
      titulo: "Com expans\u00E3o de 0,5% em julho, servi\u00E7os t\u00EAm terceira alta consecutiva",
      introducao: "O transporte de cargas (1,4%) exerceu a principal influ\u00EAncia positiva sobre o resultado do setor de servi\u00E7os no pa\u00EDs - Foto: Helena Pontes/Ag\u00EAncia IBGE Not\u00EDcias Em julho, o volume de servi\u00E7os prestados no pa\u00EDs cresceu 0,5% frente ao m\u00EAs anterior. \u00C9 a...",
      data_publicacao: "14/09/2023 09:00:00",
      produto_id: 9229,
      produtos: "9229|Pesquisa Mensal de Servi\u00E7os|pesquisa-mensal-de-servicos|2076",
      editorias: "economicas",
      imagens: "{\"image_intro\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PMS_THUMB_HelenaPontes.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PMS_HOME_HelenaPontes.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      produtos_relacionados: "9229",
      destaque: true,
      link: "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37899-com-expansao-de-0-5-em-julho-servicos-tem-terceira-alta-consecutiva.html"
    },
    {
      id: 37898,
      tipo: "Release",
      titulo: "Volume dos Servi\u00E7os cresce 0,5% em julho",
      introducao: "Em julho de 2023, o volume de servi\u00E7os no Brasil cresceu 0,5% frente a junho, na s\u00E9rie com ajuste sazonal. Foi o terceiro resultado positivo consecutivo do indicador, per\u00EDodo em que acumulou ganho de 2,2%. O setor de servi\u00E7os est\u00E1 12,8% acima do n\u00EDvel de...",
      data_publicacao: "14/09/2023 09:00:00",
      produto_id: 9229,
      produtos: "9229|Pesquisa Mensal de Servi\u00E7os|pesquisa-mensal-de-servicos|2076",
      editorias: "economicas",
      imagens: "{\"image_intro\":\"images\\/agenciadenoticias\\/releases\\/PMS_Release.png\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/releases\\/PMS_Release.png\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      produtos_relacionados: "9229",
      destaque: true,
      link: "http://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/37898-volume-dos-servicos-cresce-0-5-em-julho.html"
    },
    {
      id: 37885,
      tipo: "Not\u00EDcia",
      titulo: "Produ\u00E7\u00E3o industrial recua em quatorze dos 15 locais pesquisados em julho frente a junho",
      introducao: "O setor de equipamentos de inform\u00E1tica, produtos eletr\u00F4nicos e \u00F3pticos foi a maior influ\u00EAncia no resultado da ind\u00FAstria no Amazonas - Foto: Tiago Ciccarini/SEJUSP Na passagem de junho para julho, a produ\u00E7\u00E3o industrial brasileira recuou 0,6%, com quedas...",
      data_publicacao: "13/09/2023 09:00:00",
      produto_id: 9296,
      produtos: "9296|PIM-PF Regional#pimpf2|pesquisa-industrial-mensal-producao-fisica-regional|2209",
      editorias: "economicas",
      imagens: "{\"image_intro\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PIM-Reg_THUMB_Tiago-Ciccarini-SEJUSP.jpg\",\"float_intro\":\"\",\"image_intro_alt\":\"\",\"image_intro_caption\":\"\",\"image_fulltext\":\"images\\/agenciadenoticias\\/estatisticas_economicas\\/2023_09\\/PIM-Reg_HOME_Tiago-Ciccarini-SEJUSP.jpg\",\"float_fulltext\":\"\",\"image_fulltext_alt\":\"\",\"image_fulltext_caption\":\"\"}",
      produtos_relacionados: "9296",
      destaque: true,
      link: "http://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/37885-producao-industrial-recua-em-quatorze-dos-15-locais-pesquisados-em-julho-frente-a-junho.html"
    },
  ],
};

export default NewsData;